TrajectoryPlannerROS:
    max_vel_x: 0.35
    min_vel_x: 0.1
    max_vel_theta: 1.0
    min_in_place_vel_theta: 0.4

    acc_lim_theta: 2.2
    acc_lim_x: 1.5
    acc_lim_y: 1.5

    holonomic_robot: true
